# Generated by Django 5.0.6 on 2024-07-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Код товара')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('age_start', models.PositiveIntegerField(verbose_name='Возраст (от)')),
                ('age_end', models.PositiveIntegerField(verbose_name='Возраст (до)')),
                ('photo', models.ImageField(upload_to='products_images', verbose_name='Общий вид')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('concrete', models.FloatField(verbose_name='Бетон')),
                ('installation_time', models.FloatField(verbose_name='Время установки')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тэг товара')),
            ],
            options={
                'verbose_name': 'Тэг товара',
                'verbose_name_plural': 'Тэги товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag', verbose_name='Тэг')),
            ],
        ),
    ]
