# Generated by Django 5.0.6 on 2024-07-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_tag_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст (до)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст (от)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='concrete',
            field=models.FloatField(blank=True, null=True, verbose_name='Бетон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время установки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Общий вид'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
