# Generated by Django 5.0.7 on 2024-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_age_end_alter_product_age_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(null=True, to='shop.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='shop.tag', verbose_name='Теги'),
        ),
    ]
