# Generated by Django 5.0.6 on 2024-07-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_categories_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
