# Generated by Django 5.0.6 on 2024-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_categories_remove_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='params',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Дополнительные параметры'),
        ),
    ]
